name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name yangchichi
          git config user.email yangchichi@126.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Dependencies
        run: pip install -r docs/requirements.txt
      - name: Deploy Docs
        run: mkdocs gh-deploy --config-file mkdocs.yml --force
